environment          = "dev"
region               = "westeurope"
resource_group_name  = "tfstate"
storage_account_name = "devtfstateaks"
container_name       = "tfstate"
project_name         = "ForTech"
