name: 'Terraform Plan/Apply'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - uat
      - prod

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform-workflow:
    uses: KacperBlaz/poc-terraform-azure/.github/workflows/terraform.yaml@workflows