name: 'Terraform Plan/Apply'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - uat
      - prod

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-workflow:
    uses: KacperBlaz/poc-terraform-azure/.github/workflows/terraform.yaml@workflows